---
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_tag:
      - bastion1
      - bastion2
    region: us-east-2

  tasks:

    - name: Create vprofile ec2 key
      ec2_key:
        name: bastion-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
      when: key_out.changed

    - name: Create Security Group for Bastion Host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all ports within sg
        region: us-east-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 94.218.225.74/32
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2:
        key_name: bastion-key
        region: "{{region}}"
        instance_type: t2.micro
        image: ami-03657b56516ab7912
        wait: yes
        group: Bastion-host-sg
        wait_timeout: 300
        state: present
        instance_tags:
          Name: "{{ item }}"
       # loop: "{{instance_ids}}"
      register: bastionHost_out
      loop: "{{ instance_tag }}"
