- name: Setup RDS
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_name: my DB
    region: us-east-2
    username: admin
    password: admin123

  tasks:

    - name: set up rds
      rds:
        command: create
        instance_name: mydb
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        username: "{{username}}"
        password: "{{password}}"
        region: "{{region}}"
        tags:
          Environment: testing
          Application: cms
      register: rds_out