- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_name: my DB
    region: us-east-2


- name: set up rds
  rds:
    command: create
    instance_name: "{{instance_name}}"
    db_engine: MySQL
    size: 10
    instance_type: db.t2.micro
    username: mysql_admin
    password: 1nsecure
    tags:
      Environment: testing
      Application: cms