---
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_tag:
      - bastion1
     #- bastion2
    region: us-east-2

    instance_name: my DB
    username: admin
    password: admin123

  tasks:

    - name: Create vprofile ec2 key
      ec2_key:
        name: bastion-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
      when: key_out.changed

    - name: Create Security Group for Bastion Host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all ports within sg
        region: us-east-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 94.218.225.74/32
      register: BastionSG_out

    - name: Create Security Group for DB
      ec2_group:
        name: db-host-sg
        description: Allow port 3306 from everywhere and all ports within sg
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_id: Bastion-host-sg
      register: dbSG_out

    - name: set up rds
      rds:
        command: create
        instance_name: mydb
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        username: "{{username}}"
        password: "{{password}}"
        region: "{{region}}"
        security_groups: db-host-sg
        tags:
          Environment: testing
          Application: cms
      register: rds_out